name:                linalg
version:             0.1.0.0
github:              "conal/linalg"

description:         Please see the README on GitHub at <https://github.com/conal/linalg>

# Common language extensions defining the default language for the project.
# Un-comment each extension the first time it's used in a module.
# Undecidable* and AllowAmbiguousTypes instead go in the modules with
# a corresponding GHC error comment right after the code that generates the
# warning. See LinAlg for an example.

default-extensions:
  - CPP
  - ConstraintKinds
  - DefaultSignatures
  # - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  # - LambdaCase
  - MultiParamTypeClasses
  - PatternSynonyms
  - QuantifiedConstraints
  - RankNTypes
  - StandaloneDeriving
  # - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  # - ScopedTypeVariables
  - KindSignatures
  - TypeSynonymInstances
  - PolyKinds

ghc-options:
  -Wall

library:
  dependencies:
    - base
    - ghc-prim
    - constraints
    - distributive
    - adjunctions
    - newtype-generics
  other-modules: []
  source-dirs: src
  exposed-modules:
    - Misc
    - Category
    - LinearFunction
    - InductiveMatrix # coming
    - LinAlg          # going
    - Category.Opposite
    - Category.Isomorphism
    - Category.Index
    - Category.Constraint
    - Category.Semiring
