name:                linalg
version:             0.1.0.0
github:              "conal/linalg"

description:         Please see the README on GitHub at <https://github.com/conal/linalg>

default-extensions:
  # - AllowAmbiguousTypes
  - CPP
  - ConstraintKinds
  # - DefaultSignatures
  # - DeriveFoldable
  # - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  # - GeneralizedNewtypeDeriving
  # - LambdaCase
  - MultiParamTypeClasses
  - PatternSynonyms
  # - QuantifiedConstraints
  # - RankNTypes
  # - StandaloneDeriving
  # - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  # - UndecidableInstances
  - ViewPatterns
  # - ScopedTypeVariables
  - KindSignatures
  # - NoStarIsType
  - TypeSynonymInstances
  - PolyKinds

ghc-options:
  -Wall

library:
  dependencies:
    - base
    - ghc-prim  # GHC.Types (Constraint)
    - distributive
    - adjunctions
  other-modules: []
  source-dirs: src
  exposed-modules:
    - Misc
    - LinAlg
    - Category
    - F
